### ISSUE TITLE
It doesn’t work on iOS

### ISSUE THREAD

**Issue by korn176** [Jimbly/worlds-continent-gen#5]
*hey, remember me?*

The website doesn’t work on mobile, it doesn’t show the pop-up. What should I do?

**Comment by Jimbly** [comment]
Should work fine as long as you're using a browser like Chrome and use the two links provided in the same mobile browser.  If you're playing in an app, first create the world using a mobile browser, then switch back to the app.

**Comment by korn176** [comment]
yeah… no, it doesn’t work

**Comment by Jimbly** [comment]
You'll have to be more specific than that if you want any help, but it definitely works on Chrome on Android.

**Comment by korn176** [comment]
I’m using `Chrome on iPad` and `Safari on iPad`, both doesn’t work.

**Comment by Jimbly** [comment]
Ah, sorry, looks like the inter-page communication required for mods is not supported on iOS Safari, and Chrome on iOS just uses Safari under the hood.  You'll have to use a different device to play with mods.

**Comment by korn176** [comment]
Thanks!
